# Generated by Django 5.2.4 on 2025-07-23 18:23

import django.db.models.deletion
import hammer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('invite_code', models.CharField(default=hammer.models.generate_invite_code, max_length=10, unique=True)),
                ('code_sent', models.CharField(blank=True, max_length=4, null=True)),
                ('code_sent_at', models.DateTimeField(blank=True, null=True)),
                ('activated_invite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to='hammer.user')),
            ],
        ),
    ]
